# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80480e7c59fe3bfe5fbdf81584cd7378897fd42aad583650774967490a99bce2d0c14137cc4e197040e0db56b135069b8e6aeedf607e643d56940535778286bc

test:
  secret_key_base: a5e0c5eef50bd45930f9fbcfc150608075fcaefe2dd6fd9a05f0f90c476073ab216f04cda94f706c20612b33ff5d0c548de8730d75f164031297284cd8b79850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
